anguage: php

php:
  - 5.3

mysql:
  database: hotsause
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install git

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer
  - which composer
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - composer global require drush/drush:dev-master
  - which drush
  - sudo chmod +x build.sh
  - sh ./build.sh testbuild
  - 1
  - cd testbuild
  - drush si --db-url=mysql://root:root@localhost/hotsauce -y

script:
  - drush test-run --all
